name: FTP Deployment
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: hosting172232.ae879.netcup.net
        username: ${{ secrets.NETCUP_FTP_USERNAME }}
        password: ${{ secrets.NETCUP_FTP_PASSWORD }}